package SimulES.Model;
// Generated Aug 24, 2011 2:15:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Short adminId;
     private String name;
     private String password;

    public Admin() {
    }

    public Admin(String name, String password) {
       this.name = name;
       this.password = password;
    }
   
    public Short getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Short adminId) {
        this.adminId = adminId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


